<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="assets/style.css">
		<script src="js/script.js"></script>
		<title>Over300laughs</title>
	</head>
	<body>
		<div class="terminal-wrapper" id="terminal-sel">
			<div class="panel">
				Terminal - guest@over300laughs:~
			</div>
			<div class="terminal" id="user">
			</div>
		</div>
	</body>
</html>